// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-Ej2P23chsYi6NrbK5XYBZWRQNnzPeEg',
    appId: '1:1029504660741:web:932029cf469915fcc7f36c',
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    authDomain: 'chatapp-d72e7.firebaseapp.com',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    measurementId: 'G-DC2GY1CHXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6kDz7y3Kj48DZ9KxiirgHw-qSyKJTueg',
    appId: '1:1029504660741:android:d6593b58de10d5fcc7f36c',
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1WWvsVnAa8W6Lfheqyr9heWabwaUUizw',
    appId: '1:1029504660741:ios:405c0ac56db92c6dc7f36c',
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1WWvsVnAa8W6Lfheqyr9heWabwaUUizw',
    appId: '1:1029504660741:ios:405c0ac56db92c6dc7f36c',
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-Ej2P23chsYi6NrbK5XYBZWRQNnzPeEg',
    appId: '1:1029504660741:web:5cc169ace8eeff15c7f36c',
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    authDomain: 'chatapp-d72e7.firebaseapp.com',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    measurementId: 'G-YRM33J58KL',
  );

}