// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    authDomain: 'chatapp-d72e7.firebaseapp.com',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    measurementId: 'G-DC2GY1CHXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    messagingSenderId: '1029504660741',
    projectId: 'chatapp-d72e7',
    authDomain: 'chatapp-d72e7.firebaseapp.com',
    storageBucket: 'chatapp-d72e7.firebasestorage.app',
    measurementId: 'G-YRM33J58KL',
  );

}
